// English Translations

export default {
  // Navigation
  nav: {
    myConfessions: 'My Confessions',
    examConscience: 'Examination of Conscience',
    mySins: 'My Sins',
    prayers: 'Prayers',
    preparation: 'Preparation',
    settings: 'Settings',
    contribute: 'Contribute',
    help: 'Help',
    about: 'About',
    logout: 'Logout',
  },

  // Common
  common: {
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    ok: 'OK',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    back: 'Back',
    next: 'Next',
    remove: 'Remove',
    update: 'Update',
    user: 'User',
    yes: 'Yes',
    no: 'No',
    source: 'Source',
  },

  // Auth - Registration
  auth: {
    register: 'REGISTER',
    name: 'Name',
    namePlaceholder: 'Your name',
    themes: 'Themes:',
    languages: 'Languages:',
    createPin: 'Create your security PIN',
    pinDescription: 'This PIN will be used to protect your data',
    enterPin: 'Enter PIN:',
    confirmPin: 'Confirm PIN:',
    registerButton: 'REGISTER',
    nextButton: 'NEXT',
    backButton: 'BACK',
    // Registration errors
    errorEmptyName: 'Please enter your name.',
    errorPinLength: 'PIN must have 4 digits.',
    errorPinMatch: 'PINs do not match.',
    errorRegister: 'An error occurred while creating your account.',
    // Login
    pin: 'PIN',
    pinPlaceholder: '••••',
    login: 'LOGIN',
    forgotPin: 'FORGOT PASSWORD',
    incorrectPin: 'Incorrect PIN',
    errorOccurred: 'An error occurred',
    forgotPinTitle: 'Forgot your password?',
    forgotPinMessage: 'To reset your PIN, all your data will be deleted. Do you want to continue?',
    reset: 'Reset',
    resetSuccess: 'Your data has been deleted. You can create a new account.',
    // Import backup on registration
    haveBackup: 'Already have a backup?',
    restoreBackup: 'Restore Backup',
    restoreSuccess: 'Data restored successfully!',
  },

  // Dashboard
  dashboard: {
    lastConfession: 'LAST CONFESSION',
    myHistory: 'MY HISTORY',
    nextConfession: 'NEXT CONFESSION',
    daysWithout: "I'M %{count} DAY",
    daysWithoutPlural: "I'M %{count} DAYS",
    withoutConfessing: 'WITHOUT CONFESSING',
  },

  // History
  history: {
    title: 'My History',
    empty: 'No confessions recorded yet',
    sinForgiven: 'sin forgiven',
    sinsForgiven: 'sins forgiven',
  },

  // Examination of Conscience
  exam: {
    title: 'Examination of Conscience',
  },

  // My Sins
  sins: {
    title: 'My Sins',
    empty: 'No sins recorded',
    addSin: 'Sin',
    describeSin: 'Describe the sin:',
    inputPlaceholder: 'Type here...',
    removeSin: 'Remove sin',
    removeSinMessage: 'Do you want to remove this sin from the list?',
    reconciliare: 'RECONCILIARE',
    confessionTitle: 'Reconciliare',
    confessionMessage: 'Have you confessed and received absolution? This action will clear your list of sins and record the confession.',
    confessionConfirm: 'Yes, I confessed',
    successTitle: 'Congratulations!',
    successMessage: 'Your confession has been recorded. May God bless you!',
    warningTitle: 'Warning',
    warningMessage: 'There are no sins to confess.',
  },

  // Date Picker Modal
  datePicker: {
    title: 'Next Confession',
    subtitle: 'When do you plan to confess again?',
    addToCalendar: 'Add reminder to calendar',
  },

  // Settings
  settings: {
    title: 'Settings',
    name: 'Name',
    namePlaceholder: 'Your name',
    password: 'Password',
    currentPassword: 'Current password',
    newPassword: 'New Password',
    newPasswordPlaceholder: 'New password (4 digits)',
    themes: 'Themes:',
    languages: 'Languages:',
    update: 'UPDATE',
    pinUpdated: 'PIN updated successfully!',
    saved: 'Settings saved!',
    // Backup
    backup: 'Backup',
    exportData: 'Export Data',
    importData: 'Import Data',
    exportDescription: 'Create encrypted backup of your data',
    importDescription: 'Restore data from a previous backup',
    exportSuccess: 'Backup exported successfully!',
    importSuccess: 'Data restored successfully! Restart the app to apply changes.',
    importSuccessRestart: 'Data restored successfully! The app will restart to apply the changes.',
    importErrorFormat: 'Invalid backup file. Make sure you selected the correct file.',
    importErrorPassword: 'Incorrect PIN. Use the same PIN used to create the backup.',
    importErrorExtension: 'Invalid file. Please select a .rcl file generated by Reconciliare.',
    importErrorUnknown: 'Error importing backup. Please try again.',
    enterPinToExport: 'Enter your PIN to create the backup:',
    enterPinToImport: 'Enter the PIN used to create this backup:',
    selectBackupFile: 'Select backup file',
    noFileSelected: 'No file selected',
  },

  // Contribute
  contribute: {
    title: 'Contribute',
    text1: 'Thank you for using the RECONCILIARE app! We hope this can help with your confessions.',
    text2: 'If you would like to contribute with a donation to help maintain this project, choose one of the options below.',
    text3: 'Your contribution helps keep the app free and available for all Catholics who wish to live a life of prayer and reconciliation with God.',
    pixDescription: 'Copy the PIX key below or tap to select (Brazil only):',
    copyPix: 'COPY PIX KEY',
    copied: 'COPIED!',
    coffeeDescription: 'Support the project with an international donation:',
    buyMeACoffee: 'BUY ME A COFFEE',
    thankYou: 'May God bless you and your family!',
  },

  // Help
  help: {
    title: 'Help',
    firstAccess: 'FIRST ACCESS',
    firstAccessText: 'Registering in the app is easy, just enter your name and photo. Then enter your PIN to ensure that no one else who picks up your phone will see your examination of conscience. You can also customize the app by choosing your language and the theme you like most.',
    homeScreen: 'HOME SCREEN',
    homeScreenText: 'This screen is your dashboard, where you can view your confession history, how many days you have been without confessing, the date of your last confession and when the next one will be.',
    examConscience: 'EXAMINATION OF CONSCIENCE',
    examConscienceText: 'Before your confession, carefully read each sin and mark which ones you committed. This way each sin will be automatically transferred to your list of sins, which will show a general summary with all your sins so you can confess them to the priest. After your confession, remember to click the RECONCILIARE button, done! Just like you, your app will be clean with all sins erased.',
    prayersPreparation: 'PRAYERS AND PREPARATION',
    prayersPreparationText: 'In these sections you can recite some prayers or meditate on the sacrament of reconciliation and its importance.',
    pin: 'PIN',
    pinText: 'The PIN is a personal code with 4 numbers that protects your privacy. If you forget your PIN, you can reset it, but all the sins that are in your sin list and examination of conscience will be erased.',
    settings: 'SETTINGS',
    settingsText: 'If you want to change the theme color, your photo or your PIN, access the Settings menu and customize the app as you wish.',
  },

  // About
  about: {
    title: 'About',
    text1: 'RECONCILIARE comes from Latin and means "to reconcile", "to restore peace", "to return to friendship". This is exactly what the sacrament of Reconciliation provides us: the opportunity to reconcile with God and the Church.',
    text2: 'Jesus, with his infinite goodness, instituted the sacrament of reconciliation gifting us with His Divine Mercy. Through this sacrament, we can receive forgiveness for our sins and the grace to start anew.',
    text3: 'The RECONCILIARE app was developed to help all Catholics prepare their examination of conscience before confession. It was designed to be simple and easy to use, helping you remember your sins in order to make a good confession.',
    text4: 'May God bless you and your family!',
    version: 'Version',
  },

  // Article not found
  article: {
    notFound: 'Article not found',
  },

  // Calendar
  calendar: {
    eventTitle: 'Confession - Reconciliare',
    eventNotes: 'Reminder to confess. May God bless you!',
  },

  // Prayers
  prayers: {
    actOfContrition: {
      title: 'Act of Contrition',
      content: 'O my God, I am heartily sorry for having offended Thee, and I detest all my sins because of Thy just punishments, but most of all because they offend Thee, my God, Who art all-good and deserving of all my love. I firmly resolve, with the help of Thy grace, to sin no more and to avoid the near occasions of sin. Amen.',
    },
    actOfContritionAlt: {
      title: 'Act of Contrition (Alternative)',
      content: 'O my God, I am sorry and repent with all my heart for all the wrong I have done and for the good I have failed to do, because by sinning I have offended You, who are infinite goodness and worthy of being loved above all things. I firmly resolve, with the help of Your grace, to do penance, to sin no more and to avoid whatever leads me to sin. Amen.',
    },
    beforeConfession: {
      title: 'Prayer Before Confession',
      content: 'Lord, my God, give me light to know all my sins and grace to sincerely repent of them. Grant me humility to confess them without pride or fear. Help me approach this sacrament with faith, hope and love. May Your Holy Spirit enlighten my mind and touch my heart, so that I may make a good confession and worthily receive Your forgiveness. Through Christ our Lord. Amen.',
    },
    afterConfession: {
      title: 'Prayer After Confession',
      content: 'Lord Jesus Christ, I thank You for the gift of Your mercy that I have just received in the sacrament of Reconciliation. I thank You for forgiving my sins and restoring Your friendship to me. Help me remain faithful to the promises I made. Strengthen me with Your grace so that I do not fall into the same faults again. May the joy of Your forgiveness always accompany me and help me forgive others as You have forgiven me. Amen.',
    },
    ourFather: {
      title: 'Our Father',
      content: 'Our Father, who art in heaven, hallowed be thy name; thy kingdom come; thy will be done on earth as it is in heaven. Give us this day our daily bread; and forgive us our trespasses as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen.',
    },
    hailMary: {
      title: 'Hail Mary',
      content: 'Hail Mary, full of grace, the Lord is with thee; blessed art thou among women, and blessed is the fruit of thy womb, Jesus. Holy Mary, Mother of God, pray for us sinners, now and at the hour of our death. Amen.',
    },
    glory: {
      title: 'Glory Be',
      content: 'Glory be to the Father, and to the Son, and to the Holy Spirit. As it was in the beginning, is now, and ever shall be, world without end. Amen.',
    },
    hailHolyQueen: {
      title: 'Hail Holy Queen',
      content: 'Hail, Holy Queen, Mother of mercy, our life, our sweetness and our hope. To thee do we cry, poor banished children of Eve. To thee do we send up our sighs, mourning and weeping in this valley of tears. Turn then, most gracious advocate, thine eyes of mercy toward us, and after this our exile, show unto us the blessed fruit of thy womb, Jesus. O clement, O loving, O sweet Virgin Mary. Pray for us, O holy Mother of God, that we may be made worthy of the promises of Christ. Amen.',
    },
    creed: {
      title: 'Apostles\' Creed',
      content: 'I believe in God, the Father Almighty, Creator of heaven and earth; and in Jesus Christ, His only Son, our Lord; who was conceived by the Holy Spirit, born of the Virgin Mary; suffered under Pontius Pilate, was crucified, died and was buried. He descended into hell; the third day He rose again from the dead. He ascended into heaven, and sits at the right hand of God, the Father Almighty; from thence He shall come to judge the living and the dead. I believe in the Holy Spirit, the Holy Catholic Church, the communion of saints, the forgiveness of sins, the resurrection of the body, and life everlasting. Amen.',
    },
    saintMichael: {
      title: 'Prayer to Saint Michael the Archangel',
      content: 'Saint Michael the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil. May God rebuke him, we humbly pray; and do thou, O Prince of the Heavenly Host, by the power of God, thrust into hell Satan and all the evil spirits who prowl about the world seeking the ruin of souls. Amen.',
    },
    comeHolySpirit: {
      title: 'Come, Holy Spirit',
      content: `Come, Holy Spirit, fill the hearts of Thy faithful and enkindle in them the fire of Thy love. Send forth Thy Spirit and they shall be created. And Thou shalt renew the face of the earth.

Let us pray: O God, who didst instruct the hearts of the faithful by the light of the Holy Spirit, grant us in the same Spirit to be truly wise, and ever to rejoice in His consolation. Through Christ our Lord. Amen.`,
    },
    angelus: {
      title: 'The Angelus',
      content: `V. The Angel of the Lord declared unto Mary.
R. And she conceived of the Holy Spirit.

Hail Mary...

V. Behold the handmaid of the Lord.
R. Be it done unto me according to thy word.

Hail Mary...

V. And the Word was made flesh.
R. And dwelt among us.

Hail Mary...

V. Pray for us, O holy Mother of God.
R. That we may be made worthy of the promises of Christ.

Let us pray: Pour forth, we beseech Thee, O Lord, Thy grace into our hearts; that we, to whom the Incarnation of Christ Thy Son was made known by the message of an angel, may by His Passion and Cross be brought to the glory of His Resurrection. Through the same Christ our Lord. Amen.`,
    },
  },

  // Examination of Conscience - Categories
  examCategories: {
    firstCommandment: {
      name: 'First Commandment: Love God above all things',
      sins: [
        { id: 'p1-1', description: 'Have I neglected the knowledge of my faith, such as the Catechism teaches, such as the Apostles\' Creed, the Ten Commandments, the Seven Sacraments, the Our Father, etc.?' },
        { id: 'p1-2', description: 'Have I failed to put God first in my life?' },
        { id: 'p1-3', description: 'Have I ever consciously doubted any teaching of the Church or denied it?' },
        { id: 'p1-4', description: 'Have I doubted the existence of God?' },
        { id: 'p1-5', description: 'Have I feared Satan more than I trusted in God?' },
        { id: 'p1-6', description: 'Have I taken part in a non-Catholic act of worship?' },
        { id: 'p1-7', description: 'Am I a member of any non-Catholic religious organization, secret society or anti-Catholic group?' },
        { id: 'p1-8', description: 'Have I ever read or listened, knowing what I was doing, to any heretical, blasphemous or anti-Catholic literature, thus putting my faith at risk?' },
        { id: 'p1-9', description: 'Have I practiced any superstition (such as lucky charms, tarot, horoscope, fortune tellers, etc.)?' },
        { id: 'p1-10', description: 'Have I participated in any act of witchcraft, spiritism, occultism, fortune telling, demonic pact or sorcery?' },
        { id: 'p1-11', description: 'Have I omitted any duty or religious practice out of human respect?' },
        { id: 'p1-12', description: 'Have I failed to talk to God daily?' },
        { id: 'p1-13', description: 'Have I failed to read and live the Word of God?' },
        { id: 'p1-14', description: 'Have I failed to faithfully say my daily prayers?' },
        { id: 'p1-15', description: 'Have I abused the Sacraments in any way?' },
        { id: 'p1-16', description: 'Have I mocked God, Our Lady, the Saints, the Church, the Sacraments or any holy things?' },
        { id: 'p1-17', description: 'Have I been guilty of great irreverence in church (conversations, inattention, misconduct, the way I was dressed)?' },
        { id: 'p1-18', description: 'Have I been indifferent regarding my Catholic faith - believing that a person can be saved in any religion, or that all religions are equal?' },
        { id: 'p1-19', description: 'Have I presumed in any situation that I had God\'s mercy guaranteed?' },
        { id: 'p1-20', description: 'Have I despaired of God\'s mercy?' },
        { id: 'p1-21', description: 'Have I hated or detested God?' },
        { id: 'p1-22', description: 'Have I abandoned my faith or been ashamed of it?' },
        { id: 'p1-23', description: 'Have I idolized or given more importance to any person, activity or object than to God?' },
        { id: 'p1-24', description: 'Have I lacked faith in God, blasphemed or revolted against Him in moments of difficulty and suffering?' },
        { id: 'p1-25', description: 'Have I blasphemed against the Holy Trinity?' },
        { id: 'p1-26', description: 'Have I received Holy Communion in a state of mortal sin?' },
        { id: 'p1-27', description: 'Have I behaved badly in Church (talking, being distracted at Mass, going poorly dressed, etc.)?' },
        { id: 'p1-28', description: 'Have I failed to be supportive of the poor?' },
        { id: 'p1-29', description: 'Have I failed to help those in need?' },
        { id: 'p1-30', description: 'Have I been racist?' },
        { id: 'p1-31', description: 'Have I held grudges and resentment?' },
        { id: 'p1-32', description: 'Have I been selfish?' },
        { id: 'p1-33', description: 'Have I failed to see God in my neighbor?' },
        { id: 'p1-34', description: 'Have I failed to promote the good of my fellow man?' },
        { id: 'p1-35', description: 'Have I been negligent/uninterested in defending justice and truth?' },
      ],
    },
    secondCommandment: {
      name: 'Second Commandment: Do not take the Name of God in vain',
      sins: [
        { id: 'p2-1', description: 'Have I sworn by the Name of God unnecessarily or without reverence?' },
        { id: 'p2-2', description: 'Through words or actions, have I murmured or complained against God?' },
        { id: 'p2-3', description: 'Have I spoken injurious words against the Virgin Mary or the Saints?' },
        { id: 'p2-4', description: 'Have I cursed myself or someone or some creature?' },
        { id: 'p2-5', description: 'Have I provoked someone to anger, sin, curse, blaspheme or offend God?' },
        { id: 'p2-6', description: 'Have I broken a promise made to God?' },
        { id: 'p2-7', description: 'Have I used the name of God in vain or with anger?' },
      ],
    },
    thirdCommandment: {
      name: 'Third Commandment: Keep Holy the Sundays and Holy Days of Obligation',
      sins: [
        { id: 'p3-1', description: 'Have I failed to participate in Holy Mass on Sundays or Holy Days of Obligation?' },
        { id: 'p3-2', description: 'Have I arrived late or left before the end of Mass without serious reason?' },
        { id: 'p3-3', description: 'Have I gone to Mass only when I felt like it?' },
        { id: 'p3-4', description: 'Have I caused others to miss Mass on Sundays and Holy Days of Obligation, or to leave early or arrive late?' },
        { id: 'p3-5', description: 'Have I been deliberately inattentive during Mass?' },
        { id: 'p3-6', description: 'Have I played or been disrespectful in church?' },
        { id: 'p3-7', description: 'Have I failed to pay my tithe?' },
        { id: 'p3-8', description: 'Have I failed to participate in parish activities?' },
        { id: 'p3-9', description: 'Have I failed to give witness to Christian life?' },
        { id: 'p3-10', description: 'Have I shown no interest in the things of the Catholic Church?' },
        { id: 'p3-11', description: 'Have I failed to go to confession frequently?' },
        { id: 'p3-12', description: 'Have I confessed without the firm purpose of amending myself?' },
        { id: 'p3-13', description: 'Have I failed to fast and abstain from meat on the prescribed days?' },
        { id: 'p3-14', description: 'Have I worked or made someone work on Sunday or Holy Day of Obligation without necessity?' },
        { id: 'p3-15', description: 'Have I bought or sold things without necessity on Sundays and Holy Days of Obligation?' },
      ],
    },
    fourthCommandment: {
      name: 'Fourth Commandment: Honor your father and mother',
      sins: [
        { id: 'p4-1', description: 'Have I disobeyed my parents, disrespected them, neglected to help them in their needs or refused to do so?' },
        { id: 'p4-2', description: 'Have I shown irreverence/disrespect toward people in positions of authority?' },
        { id: 'p4-3', description: 'Have I disobeyed legitimate authorities?' },
        { id: 'p4-4', description: 'Have I insulted or spoken ill of priests or other persons consecrated to God?' },
        { id: 'p4-5', description: 'Have I had less reverence for elderly people?' },
        { id: 'p4-6', description: 'Have I mistreated my spouse or my children?' },
        { id: 'p4-7', description: 'Have I put my spouse in second place?' },
        { id: 'p4-8', description: 'Have I been disobedient or disrespectful to my spouse?' },
        { id: 'p4-9', description: 'Have I neglected my family\'s needs? (material, presence, etc.)' },
        { id: 'p4-10', description: 'Have I failed to baptize my children early?' },
        { id: 'p4-11', description: 'Have I failed to teach the Catholic faith and religious practice to my children?' },
        { id: 'p4-12', description: 'Have I allowed my children to neglect their religious duties?' },
        { id: 'p4-13', description: 'Have I allowed my children to date without a clear intention of leading the relationship to marriage?' },
        { id: 'p4-14', description: 'Have I allowed my children to have sexual relations outside of marriage?' },
        { id: 'p4-15', description: 'Have I allowed my children to watch pornography or immoral content?' },
        { id: 'p4-16', description: 'Have I failed to watch over the company my children keep?' },
        { id: 'p4-17', description: 'Have I abandoned my responsibilities as a father/mother?' },
        { id: 'p4-18', description: 'Have I failed to discipline my children when they needed correction?' },
        { id: 'p4-19', description: 'Have I set a bad example for my children?' },
        { id: 'p4-20', description: 'Have I scandalized my children by arguing with my spouse in front of them?' },
        { id: 'p4-21', description: 'Have I scandalized my children by saying profanity and obscenities in front of them?' },
        { id: 'p4-22', description: 'Have I failed to keep modesty in my home?' },
        { id: 'p4-23', description: 'Have I been rude at home?' },
        { id: 'p4-24', description: 'Have I fought or argued frequently?' },
        { id: 'p4-25', description: 'Have I been impatient and/or authoritarian?' },
        { id: 'p4-26', description: 'Have I lacked dialogue and love at home?' },
        { id: 'p4-27', description: 'Have I failed to pray as a family?' },
        { id: 'p4-28', description: 'Have I allowed my children to wear immodest clothing (mini-skirts, tight pants, tight dresses, transparent blouses, very short shorts, revealing swimwear, etc.)?' },
        { id: 'p4-29', description: 'Have I denied my children the freedom to marry or follow a religious vocation?' },
        { id: 'p4-30', description: 'Have I failed to forgive my family members for offenses?' },
        { id: 'p4-31', description: 'Have I been ashamed of my family members?' },
        { id: 'p4-32', description: 'Have I caused sadness to my family members?' },
        { id: 'p4-33', description: 'Have I disrupted family harmony?' },
        { id: 'p4-34', description: 'Have I caused disruption and disturbed classes at school?' },
        { id: 'p4-35', description: 'Have I been negligent at school or work?' },
        { id: 'p4-36', description: 'Have I been irresponsible with my studies and school duties?' },
        { id: 'p4-37', description: 'Have I disrespected teachers and classmates?' },
        { id: 'p4-38', description: 'Have I committed any type of aggression against a family member?' },
      ],
    },
    fifthCommandment: {
      name: 'Fifth Commandment: You shall not kill',
      sins: [
        { id: 'p5-1', description: 'Do I not accept myself as I am?' },
        { id: 'p5-2', description: 'Have I sought or desired to end my life?' },
        { id: 'p5-3', description: 'Have I wished or hastened the death or injury of someone?' },
        { id: 'p5-4', description: 'Have I harbored hatred toward someone?' },
        { id: 'p5-5', description: 'Have I oppressed someone?' },
        { id: 'p5-6', description: 'Have I desired revenge?' },
        { id: 'p5-7', description: 'Have I provoked distrust or discord among others?' },
        { id: 'p5-8', description: 'Have I argued or fought with someone?' },
        { id: 'p5-9', description: 'Have I wished harm on someone?' },
        { id: 'p5-10', description: 'Have I wanted to hurt or mistreat someone?' },
        { id: 'p5-11', description: 'Do I refuse to speak to someone, or hold resentment toward someone?' },
        { id: 'p5-12', description: 'Have I rejoiced in the misfortune of others?' },
        { id: 'p5-13', description: 'Have I been jealous or envious of someone?' },
        { id: 'p5-14', description: 'Have I had, attempted or advised someone to have an abortion?' },
        { id: 'p5-15', description: 'Have I mutilated my body unnecessarily?' },
        { id: 'p5-16', description: 'Have I consented to suicidal thoughts or attempted against my life?' },
        { id: 'p5-17', description: 'Have I become intoxicated or used illicit drugs?' },
        { id: 'p5-18', description: 'Have I eaten excessively, committing the sin of gluttony?' },
        { id: 'p5-19', description: 'Have I mistreated, injured or killed any animal or creature of God without necessity?' },
        { id: 'p5-20', description: 'Have I unnecessarily wasted natural resources (water) or food?' },
        { id: 'p5-21', description: 'Have I failed to eat enough due to neglect of my health?' },
        { id: 'p5-22', description: 'Have I failed to dedicate time to rest and leisure?' },
        { id: 'p5-23', description: 'Have I worked too much, harming my health?' },
        { id: 'p5-24', description: 'Have I taken medicine without necessity or abusively?' },
        { id: 'p5-25', description: 'Have I failed to correct someone in a fraternal and charitable way?' },
        { id: 'p5-26', description: 'Have I caused damage to someone\'s soul, especially children, by giving bad examples?' },
        { id: 'p5-27', description: 'Have I harmed my soul, intentionally and unnecessarily exposing it to temptations?' },
        { id: 'p5-28', description: 'Have I harmed my body, putting it at risk and not caring for it as a temple of the Holy Spirit?' },
        { id: 'p5-29', description: 'Have I risked my life without necessity?' },
        { id: 'p5-30', description: 'Have I failed to avoid laziness and idleness?' },
        { id: 'p5-31', description: 'Have I been reckless, driving at high speed or under the influence of alcohol/drugs or used my phone while driving?' },
        { id: 'p5-32', description: 'Have I disrespected traffic laws, putting people\'s lives at risk?' },
        { id: 'p5-33', description: 'Have I refused to respect nature and the environment?' },
      ],
    },
    sixthNinthCommandment: {
      name: 'Sixth and Ninth Commandments: Do not sin against chastity / Do not covet your neighbor\'s wife',
      sins: [
        { id: 'p6-1', description: 'Have I denied my spouse conjugal relations without just reason?' },
        { id: 'p6-2', description: 'Have I practiced artificial birth control (condoms, pills, IUD, vasectomy, tubal ligation)?' },
        { id: 'p6-3', description: 'Have I abused my marital rights in any other way?' },
        { id: 'p6-4', description: 'Have I committed adultery in my marriage (in thoughts, looks, words or acts)?' },
        { id: 'p6-5', description: 'Have I practiced unnatural sexual acts (anal sex)?' },
        { id: 'p6-6', description: 'Have I practiced pedophilia?' },
        { id: 'p6-7', description: 'Have I practiced sexual relations outside of marriage (fornication)?' },
        { id: 'p6-8', description: 'Have I committed the sin of fornication with my boyfriend/girlfriend outside of marriage?' },
        { id: 'p6-9', description: 'Have I committed any impure sin against nature (homosexuality or lesbianism, etc.)?' },
        { id: 'p6-10', description: 'Have I caused scandals?' },
        { id: 'p6-11', description: 'Have I participated in orgies?' },
        { id: 'p6-12', description: 'Have I participated in impure conversations?' },
        { id: 'p6-13', description: 'Have I had sexual relations with prostitutes or gone to nightclubs where prostitution occurs?' },
        { id: 'p6-14', description: 'Have I touched or embraced another person with sexual desire outside of marriage?' },
        { id: 'p6-15', description: 'Have I exchanged prolonged kisses in my dating or engagement?' },
        { id: 'p6-16', description: 'Have I touched the intimate parts of my boyfriend/girlfriend or fiancé/fiancée?' },
        { id: 'p6-17', description: 'Have I practiced prolonged exchange of caresses in my dating or engagement?' },
        { id: 'p6-18', description: 'Have I sinned impurely against myself (masturbation)?' },
        { id: 'p6-19', description: 'Have I let myself be carried away by sexual fantasies, such as vibrators, erotic clothing or sex toys?' },
        { id: 'p6-20', description: 'Have I consented to impure thoughts, or taken pleasure in them?' },
        { id: 'p6-21', description: 'Have I consented to impure desires for someone, or consciously desired to see or do something impure?' },
        { id: 'p6-22', description: 'Have I treated my spouse as an object of sexual pleasure?' },
        { id: 'p6-23', description: 'Have I been an occasion of sin for others, by wearing tight, revealing or immodest clothing?' },
        { id: 'p6-24', description: 'Have I done anything, deliberately or carelessly, that provoked impure thoughts or desires in another person?' },
        { id: 'p6-25', description: 'Have I read indecent books or viewed obscene images?' },
        { id: 'p6-26', description: 'Have I watched movies, TV programs or pornography on the internet?' },
        { id: 'p6-27', description: 'Do I still keep any pornographic material?' },
        { id: 'p6-28', description: 'Have I used indecent language or told indecent stories?' },
        { id: 'p6-29', description: 'Have I willingly listened to indecent stories or jokes?' },
        { id: 'p6-30', description: 'Have I boasted about my sexual sins, or enjoyed recalling past sins?' },
        { id: 'p6-31', description: 'Have I been in indecent company?' },
        { id: 'p6-32', description: 'Have I consented to impure looks, desiring other people?' },
        { id: 'p6-33', description: 'Have I failed to control my imagination with impure thoughts?' },
        { id: 'p6-34', description: 'Have I failed to pray immediately to ward off bad thoughts and temptations?' },
        { id: 'p6-35', description: 'Have I failed to avoid occasions of impurity?' },
        { id: 'p6-36', description: 'Have I gone to immodest dances or indecent theater performances?' },
        { id: 'p6-37', description: 'Have I been alone unnecessarily in the company of someone of the opposite sex, with bad intention?' },
      ],
    },
    seventhTenthCommandment: {
      name: 'Seventh and Tenth Commandments: Do not steal / Do not covet your neighbor\'s goods',
      sins: [
        { id: 'p7-1', description: 'Have I stolen anything?' },
        { id: 'p7-2', description: 'Have I damaged or destroyed another person\'s property?' },
        { id: 'p7-3', description: 'Have I let another person\'s property be damaged through negligence?' },
        { id: 'p7-4', description: 'Have I been negligent in guarding another person\'s money or goods?' },
        { id: 'p7-5', description: 'Have I gambled excessively or bet irresponsibly?' },
        { id: 'p7-6', description: 'Have I deceived someone, been negligent or refused to pay my debts?' },
        { id: 'p7-7', description: 'Have I acquired something that I knew was stolen?' },
        { id: 'p7-8', description: 'Have I failed to return something borrowed?' },
        { id: 'p7-9', description: 'Have I cheated my employer, not working as expected or in expenses?' },
        { id: 'p7-10', description: 'Have I been dishonest with my employees\' wages?' },
        { id: 'p7-11', description: 'Have I refused to help someone who urgently needed help, or been negligent in doing so?' },
        { id: 'p7-12', description: 'Have I failed to return what I stole, or obtained by fraud?' },
        { id: 'p7-13', description: 'Have I been envious of someone for having something I don\'t have?' },
        { id: 'p7-14', description: 'Have I envied someone\'s goods?' },
        { id: 'p7-15', description: 'Have I been greedy?' },
        { id: 'p7-16', description: 'Have I oppressed, belittled or been prejudiced against someone for being poorer than me?' },
        { id: 'p7-17', description: 'Have I given too much importance to material goods and comforts?' },
        { id: 'p7-18', description: 'Have I bribed someone?' },
        { id: 'p7-19', description: 'Have I been responsible for or participated in any act of corruption?' },
        { id: 'p7-20', description: 'Have I kept found objects without looking for the owner? (when possible)' },
        { id: 'p7-21', description: 'Have I cheated in business dealings?' },
        { id: 'p7-22', description: 'Have I diverted materials from public or private companies?' },
        { id: 'p7-23', description: 'Have I disrespected the just laws of the State and municipality?' },
        { id: 'p7-24', description: 'Have I committed fraud or evaded taxes?' },
        { id: 'p7-25', description: 'Have I caused harm to someone through my fault (bad check, etc.)?' },
        { id: 'p7-26', description: 'Have I sought abusive profits by exploiting others?' },
      ],
    },
    eighthCommandment: {
      name: 'Eighth Commandment: Do not bear false witness',
      sins: [
        { id: 'p8-1', description: 'Have I lied?' },
        { id: 'p8-2', description: 'Have I lied about someone (slander)?' },
        { id: 'p8-3', description: 'Have my lies caused someone material or spiritual harm?' },
        { id: 'p8-4', description: 'Have I made prejudiced judgments about someone?' },
        { id: 'p8-5', description: 'Have I spoken ill of someone (slander, defamation or gossip)?' },
        { id: 'p8-6', description: 'Have I revealed the sins or faults of another person without necessity?' },
        { id: 'p8-7', description: 'Have I revealed secrets entrusted to me?' },
        { id: 'p8-8', description: 'Have I been guilty of causing intrigues or enmities?' },
        { id: 'p8-9', description: 'Have I given credit or support to the spreading of scandals about my neighbor?' },
        { id: 'p8-10', description: 'Have I sown discord among people through slander?' },
        { id: 'p8-11', description: 'Have I borne false witness against my neighbor?' },
        { id: 'p8-12', description: 'Have I sworn falsely or signed false documents?' },
        { id: 'p8-13', description: 'Am I critical or negative without necessity?' },
        { id: 'p8-14', description: 'Do I lack charity in my conversations?' },
        { id: 'p8-15', description: 'Have I ever caused others to sin?' },
        { id: 'p8-16', description: 'Have I cooperated in the sins of others?' },
        { id: 'p8-17', description: 'Have I failed to repair the harm I have done to others?' },
      ],
    },
    capitalSins: {
      name: 'Capital Vices/Sins',
      sins: [
        { id: 'vc-1', description: 'Pride: Have I fallen into activism?' },
        { id: 'vc-2', description: 'Pride: Have I considered myself better than others?' },
        { id: 'vc-3', description: 'Pride: Have I sought to draw attention to myself?' },
        { id: 'vc-4', description: 'Pride: Have I been hypocritical and fake?' },
        { id: 'vc-5', description: 'Pride: Have I had delusions of grandeur?' },
        { id: 'vc-6', description: 'Pride: Have I criticized people destructively?' },
        { id: 'vc-7', description: 'Pride: Have I belittled the doctrine of the Catholic Church?' },
        { id: 'vc-8', description: 'Envy: Have I envied the gifts, goods or fame of others?' },
        { id: 'vc-9', description: 'Envy: Do I want to be an irreplaceable servant in my community?' },
        { id: 'vc-10', description: 'Envy: Have I failed to develop the gifts God gave me?' },
        { id: 'vc-11', description: 'Wrath: Have I been impatient?' },
        { id: 'vc-12', description: 'Wrath: Have I been resentful or vindictive?' },
        { id: 'vc-13', description: 'Wrath: Have I been aggressive or nervous?' },
        { id: 'vc-14', description: 'Greed: Have I been attached to money and material things?' },
        { id: 'vc-15', description: 'Greed: Have I sought to live in luxury?' },
        { id: 'vc-16', description: 'Greed: Have I failed to share my goods?' },
        { id: 'vc-17', description: 'Sloth: Have I been lazy in praying, working or helping people?' },
        { id: 'vc-18', description: 'Sloth: Am I uninterested in building a more just, fraternal and Christian world?' },
        { id: 'vc-19', description: 'Sloth: Have I failed to take an evangelical stance by not denouncing injustices, misery, hunger, violence, prejudice, discrimination, eroticism, signs of death, consumerism?' },
        { id: 'vc-20', description: 'Gluttony: Have I exceeded in eating?' },
        { id: 'vc-21', description: 'Gluttony: Have I lost control in drinking?' },
        { id: 'vc-22', description: 'Gluttony: Have I exceeded in smoking?' },
        { id: 'vc-23', description: 'Gluttony: Have I consumed drugs?' },
      ],
    },
    churchCommandments: {
      name: 'Precepts of the Church and the Holy Mass',
      sins: [
        { id: 'pi-1', description: 'Have I failed to participate in Holy Mass on Sundays and Holy Days of Obligation?' },
        { id: 'pi-2', description: 'Have I failed to observe fasting or abstinence on prescribed dates?' },
        { id: 'pi-3', description: 'Have I failed to observe the Eucharistic fast (1 hour before communion)?' },
        { id: 'pi-4', description: 'Have I failed to confess at least once a year?' },
        { id: 'pi-5', description: 'Have I failed to receive the Holy Eucharist at least once a year?' },
        { id: 'pi-6', description: 'Having income from my work, have I failed to contribute to the tithe or parish expenses?' },
        { id: 'pi-7', description: 'Have I failed to observe the laws of the Church regarding Marriage, that is, regarding Marriage without the presence of a priest, or in the case of marriage to a close relative or a non-Catholic?' },
        { id: 'pi-8', description: 'Have I received the Eucharist without preparation/devotion or spirit of adoration?' },
        { id: 'pi-9', description: 'Have I been talking during Holy Mass?' },
        { id: 'pi-10', description: 'Have I used my cell phone during Holy Mass without justification?' },
        { id: 'pi-11', description: 'Have I judged the people who were serving at the altar or participating in Mass?' },
        { id: 'pi-12', description: 'Have I spoken ill of the Priest, his posture or the homily?' },
        { id: 'pi-13', description: 'Has my posture at Mass been one of carelessness, negligence or laziness?' },
        { id: 'pi-14', description: 'Have I been sleeping during the homily?' },
        { id: 'pi-15', description: 'Have I shown aversion to the rites performed at Holy Mass?' },
        { id: 'pi-16', description: 'Have I failed to cooperate in the participation of each rite, neither in silence, nor with joy, nor with faith?' },
        { id: 'pi-17', description: 'Have I been omitting participation in some liturgical rite such as doing a reading, making excuses that I am not capable, that I don\'t know how to do it, or out of shame?' },
      ],
    },
    blasphemiesMary: {
      name: 'Blasphemies against the Immaculate Heart of Mary',
      sins: [
        { id: 'bm-1', description: 'Have I blasphemed against the Immaculate Conception?' },
        { id: 'bm-2', description: 'Have I blasphemed against the Perpetual Virginity of Our Lady?' },
        { id: 'bm-3', description: 'Have I blasphemed against the Divine Motherhood of Our Lady?' },
        { id: 'bm-4', description: 'Have I failed to recognize Our Lady as Mother of all men?' },
        { id: 'bm-5', description: 'Have I tried to sow in the hearts of children indifference, contempt or hatred toward Our Lady?' },
        { id: 'bm-6', description: 'Have I despised or ridiculed Mary or the Saints in their holy images?' },
      ],
    },
    mercyWorks: {
      name: 'Spiritual and Corporal Works of Mercy',
      sins: [
        { id: 'om-1', description: 'Have I omitted or failed to give good counsel to those who sin?' },
        { id: 'om-2', description: 'Have I failed to instruct the ignorant?' },
        { id: 'om-3', description: 'Have I failed to counsel those who doubt the faith?' },
        { id: 'om-4', description: 'Have I failed to comfort the sorrowful?' },
        { id: 'om-5', description: 'Have I failed to suffer/bear patiently the weaknesses of my neighbor?' },
        { id: 'om-6', description: 'Have I failed to forgive my brothers for love of God?' },
        { id: 'om-7', description: 'Have I failed to pray for the living and the dead?' },
        { id: 'om-8', description: 'Have I failed to feed the hungry?' },
        { id: 'om-9', description: 'Have I failed to give drink to the thirsty?' },
        { id: 'om-10', description: 'Have I failed to clothe the naked?' },
        { id: 'om-11', description: 'Have I failed to visit the imprisoned?' },
        { id: 'om-12', description: 'Have I failed to help or shelter the homeless?' },
        { id: 'om-13', description: 'Have I failed to visit the sick?' },
        { id: 'om-14', description: 'Have I failed to bury the dead or visit the cemetery at least once a year?' },
      ],
    },
  },

  // Preparation Articles
  articles: {
    whatIsSin: {
      title: 'What is Sin?',
      content: `The concept of sin is quite simple: basically, sin is an act of exaggerated selfishness. It is preferring oneself, putting oneself before God and others, yielding to disordered passions that place us at the center of our existence, denying our nature, which is only complete when it opens to others and to God.

Sin is the rejection of establishing a relationship of love with God and others. It is "closing oneself to creatures" and "rejecting the Creator." In general, the sinner only desires the pleasures provided by creatures, and does not necessarily want to reject the Creator.

But, by allowing oneself to be seduced by the fleeting satisfactions provided by creatures, the sinner is implicitly acting against the love of the Creator, because they feel that earthly pleasure does not fulfill them, but still cannot resist it.

Therefore, sin wounds the sinner themselves, distancing them from the fullness offered by God. And therefore, sin offends God: not because God, as such, is affected, but because we ourselves, when we sin, diminish ourselves before the greatness that God offers us.

For Jesus, sin is born within man (cf. Mt 15:10-20). Therefore, interior transformation, of the heart, is necessary. For Jesus, sin is slavery: man lets himself be in the power of the evil one, falsely valuing the things of this world, letting himself be carried away by the immediate, by sensible satisfactions, which do not satisfy our thirst for love and fullness.

## What types of sin exist?

**Original Sin:** It is the inheritance we all receive from our first parents, Adam and Eve: they distrusted the love of God the Father and yielded to the temptation to leave him out of their personal choices. As children of a humanity that lost its innocence, we are all born with the fallen nature of sinners and need the grace of God, through the sacrament of Baptism, to purify our soul.

**Actual or Personal Sin:** It is what we commit as individuals, voluntarily and consciously. It can be committed in four ways:
- With thoughts
- With words
- With actions
- With omissions

And it can be against God, against neighbor or against ourselves.

## Mortal and Venial Sin

Personal sin can be **mortal** or **venial**:

1. **Venial Sin (light):** One we commit without full awareness or without full consent, but in light matter.
2. **Mortal Sin (grave):** Involves three simultaneous factors: full awareness, full consent and grave matter.

## What is grave matter and light matter?

The "matter" is the sinful "fact" itself.

**Grave matter:** Seriously wounds any of the 10 commandments. Some examples:
- Denying the existence of God
- Offending God or parents
- Killing or seriously injuring a person
- Putting oneself at serious risk of death without just reason
- Committing impure acts
- Stealing valuable objects
- Slandering
- Committing serious omissions in the fulfillment of duty
- Causing scandal to neighbor

**Light matter:** Does not seriously wound any of the 10 commandments, even if it consists of an act contrary to some of them.`,
      source: 'Aleteia',
    },
    mortalSins: {
      title: 'Mortal Sins',
      content: `When we commit a grave sin we expel God from us and lose sanctifying grace. That is why sin is the greatest disgrace that exists in the world.

To sin gravely is:
- To act against the will of God
- To attempt against His glory
- To offend the One who is infinitely good
- To deprive oneself of the grace of God
- To submit to the slavery of the Devil
- To become a candidate for Hell

## Definition

**Mortal sin** is thinking, desiring, saying, doing, or omitting something against the law of God in grave matter, knowing it and wanting it.

Three elements are necessary:
1. **Grave matter**
2. **Knowledge** (knowing it is a sin)
3. **Freedom** (wanting to do it)

## Examples of grave matter

- Not believing something taught by God and the Church, or worshiping other gods *(against the 1st commandment)*
- Blaspheming the Holy name of God, the Virgin and the Saints *(against the 2nd commandment)*
- Missing Mass on Sundays and Holy Days, without grave reason *(against the 3rd commandment)*
- Killing, committing suicide, abortion: "abominable crime" *(Vatican Council II)*
- Consenting to evil thoughts, desires, looks, conversations, actions against purity, fidelity, or the transmission of life
- Stealing a significant amount
- Slandering or defaming a person in something grave`,
      source: 'Shalom Community',
    },
    venialSins: {
      title: 'Venial Sins',
      content: `There is another type of sin: **venial** or light sin.

This sin:
- Does not deprive the soul of the grace of God
- Does not condemn it to Hell

However, it:
- Prevents perfection
- Hinders the soul's journey toward God
- Leads to vice and the slavery of sin
- Causes relaxation of conscience
- Cools the love for God
- Can lead to more serious sins

## Definition

**Venial sin** is thinking, desiring, saying, doing or omitting something against the law of God in light matter.

## Difference between Mortal and Venial

| Mortal Sin | Venial Sin |
|------------|------------|
| Punishment: Eternal Hell | Penalty: Temporary Purgatory |
| Only forgiven through confession (or act of perfect contrition with purpose to confess) | Forgiven by sincere repentance |

## How to obtain forgiveness for venial sin

- Sincere repentance
- Good works
- Prayer
- Almsgiving
- Holy water
- Sign of the cross
- Confession`,
      source: 'Shalom Community',
    },
    tenCommandments: {
      title: 'The Ten Commandments',
      content: `The Ten Commandments or Decalogue is the name given to the set of laws that according to the Bible, would have been originally written by God on stone tablets and given to the prophet Moses (the Tablets of the Law).

## The Commandments

**1st** - I am the Lord your God: you shall not have strange gods before me.

**2nd** - You shall not take the name of the Lord your God in vain.

**3rd** - Remember to keep holy the Lord's Day.

**4th** - Honor your father and your mother (and other legitimate superiors).

**5th** - You shall not kill (nor cause other harm, in body or soul, to yourself or your neighbor).

**6th** - You shall not commit adultery.

**7th** - You shall not steal (nor unjustly retain or damage your neighbor's goods).

**8th** - You shall not bear false witness against your neighbor (nor in any other way fail to tell the truth or defame your neighbor).

**9th** - You shall not covet your neighbor's wife.

**10th** - You shall not covet your neighbor's goods.`,
      source: 'Wiki',
    },
    sinsVsVirtues: {
      title: 'Sins vs Virtues',
      content: `The Catholic Church considers that every human being is, in essence, good. Therefore, for each of the 7 capital sins, there is an opposite virtue:

## The 7 Sins and their Virtues

| Sin | Virtue |
|-----|--------|
| **Pride** | Humility |
| **Greed** | Generosity |
| **Lust** | Chastity |
| **Envy** | Charity |
| **Gluttony** | Temperance |
| **Wrath** | Patience |
| **Sloth** | Diligence |

## Reflection

The practice of virtues is the way to overcome vices. It is not enough to avoid sin; we must actively cultivate the opposite virtue.

For example:
- To overcome **pride**, practice acts of **humility**
- To overcome **greed**, exercise **generosity**
- To overcome **wrath**, cultivate **patience**`,
      source: '',
    },
    meditation: {
      title: 'Meditation',
      content: `I believe in a Savior who loves me, who forgives my sins and who gives me the grace to become holy. Jesus Christ, through the ministry of His priests, does both in the Sacrament of Penance.

## Words of Scripture

> "As the Father has sent Me, even so I send you... Receive the Holy Spirit. If you forgive the sins of any, they are forgiven; if you retain the sins of any, they are retained."
> — John 20:21-23

> "Though your sins are like scarlet, they shall be as white as snow."
> — Isaiah 1:18

> "I came not to call the righteous, but sinners."
> — Matthew 9:13

## The Power of the Priest

Saint John Chrysostom teaches:

> "Men have received from God a power that has not been given to angels or archangels. It was never said to heavenly spirits: 'Whatever you bind and loose on earth shall be bound and loosed in heaven.' The princes of this world can only bind and loose the body. The power of the priest goes further; it reaches the soul, and is exercised not only in baptizing, but even more in forgiving sins."

## Practical Advice

- Do not be afraid to confess to the priest any impure sin you have committed
- Do not hide or try to disguise it
- The priest is there to help and forgive
- Nothing you say will scandalize him

**Remember:** Confess your sins with supernatural repentance, having a firm resolution not to sin again and to avoid situations that lead to sin.`,
      source: 'Fatima.org',
    },
    howToConfess: {
      title: 'How to Confess',
      content: `## Preparation

First of all, **examine your conscience well**.

Then tell the priest:
- What specific sins you committed
- As accurately as possible, how many times you committed them since your last good confession

## What to confess

You are only **obliged** to confess mortal sins, since you can obtain forgiveness for venial sins through sacrifices and acts of charity.

> **Tip:** If you are in doubt whether a sin is mortal or venial, mention your doubt to the confessor.

Confession of venial sins is also recommended, as it greatly helps to avoid sin and advance toward Heaven.

## Conditions for a sin to be mortal

1. **Serious matter** - the act itself is grave
2. **Sufficient reflection** - knowing it is a sin
3. **Full consent** - choosing to do it freely

## Important warnings

- **Deliberately hiding** a mortal sin invalidates the confession, and is itself a mortal sin
- Confession is **private** and subject to the **Seal of Confession**
- It is a mortal sin for a priest to reveal to anyone the matter of a confession`,
      source: 'Fatima.org',
    },
    spiritualDirection: {
      title: 'Spiritual Direction',
      content: `If you have spiritual direction, you already know the importance of this guidance for keeping the interior life going and, in general, for progressing in the Christian life.

## Why have a spiritual director?

The Church has always recommended spiritual direction to all who wish to mature seriously in the Christian life, analogous to:
- A heart patient who seeks the guidance of a cardiologist
- An athlete who has a coach to prepare and guide them

**No one is a good coach of themselves.**

## Teaching of Saint Josemaría Escrivá

> "You should know this sure doctrine: one's own spirit is a bad pilot, to guide the soul in the storms and tempests, among the reefs of the interior life. Therefore, it is God's will that the direction of the ship be entrusted to a Master, so that, with his light and knowledge, he may lead us to a safe port."
> — The Way, n. 59

## The Good Shepherd

The confessor and, in general, the person who attends to the spiritual direction of others, participates in the mission of the Good Shepherd:

- Knows his sheep and they know him
- Shows them the way
- Leads them to good pastures
- Defends them from thieves and the wolf (cf. Jn 10:4-14)
- Seeks those who have strayed to help them return (cf. Lk 15:4-7)

## How to choose a director

The good spiritual director must be a reflection of Jesus, the Good Shepherd.

**Important:** Ask the Holy Spirit for lights to choose well the director — always with full freedom, but with the sincere desire to advance spiritually.`,
      source: 'Fr. Francisco Faus',
    },
    spiritualAdvice: {
      title: 'Spiritual Advice',
      content: `> "There are no strong or weak people: there are people who pray and people who do not pray."

Saint Augustine said that whoever prays well, lives well; whoever lives well, dies well; and for whoever dies well, all is well.

Saint Alphonsus teaches: *"Whoever prays much will be saved. Whoever prays little puts their eternal salvation at risk."*

## 10 Tips for Growing in Prayer

### 1. Have conviction and determination
No one succeeds in any area of life without determination. Athletes, musicians, scholars did not get where they are just by wishing.

### 2. Hire the Holy Spirit as teacher
Saint Paul teaches us that we do not know how to pray as we ought, and that it is the Holy Spirit who intercedes for us. Before beginning any moment of prayer, invoke the Holy Spirit to enlighten your mind and set your heart on fire.

### 3. Dedicate time, space, goodwill and silence
Like any art is learned by practice, this also applies to prayer. Choose a specific time, a good place, put the best of yourself into it and make interior silence.

### 4. Do penance
If your prayer has become boring and you are no longer growing spiritually, it may be due to neglect in the life of penance. Consult a good spiritual director and start with small acts.

### 5. Seek spiritual direction
Athletes need coaches; students need teachers. Prayer warriors need a guide.

### 6. Pray and live the action
An authentic life of prayer reaches its fullness in the progressive practice of virtues: faith, hope, charity, purity, kindness, service, humility.

### 7. Study and read about prayer
Saint Teresa of Ávila did not accept nuns into her convent who could not read. The saint knew how important it is to learn about prayer through solid spiritual reading.

### 8. Participate in retreats
Retreats allow for a more prolonged dedication to prayer. One of the most effective styles are Ignatian retreats.

### 9. Confess regularly
Sometimes prayer becomes very difficult because our conscience is dirty with sin. Jesus said: *"Blessed are the pure in heart, for they shall see God"* (Mt 5:8).

### 10. Count on Our Lady
After invoking the Holy Spirit, ask for Mary's intercession for you, and invite her to be at your side every time you dedicate time to prayer. **She never fails.**`,
      source: 'Aleteia.org',
    },
  },
};
